// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int32                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListRequest) Reset() {
	*x = RoomListRequest{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListRequest) ProtoMessage() {}

func (x *RoomListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListRequest.ProtoReflect.Descriptor instead.
func (*RoomListRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *RoomListRequest) GetProfileId() int32 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type RoomListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomGeneral   []*RoomGeneral         `protobuf:"bytes,1,rep,name=room_general,json=roomGeneral,proto3" json:"room_general,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListResponse) Reset() {
	*x = RoomListResponse{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListResponse) ProtoMessage() {}

func (x *RoomListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListResponse.ProtoReflect.Descriptor instead.
func (*RoomListResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *RoomListResponse) GetRoomGeneral() []*RoomGeneral {
	if x != nil {
		return x.RoomGeneral
	}
	return nil
}

type RoomGeneral struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomTile       string                 `protobuf:"bytes,2,opt,name=room_tile,json=roomTile,proto3" json:"room_tile,omitempty"`
	ClientId       int32                  `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ProfileId      int32                  `protobuf:"varint,4,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	ProfileName    string                 `protobuf:"bytes,5,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	ProfileSurname string                 `protobuf:"bytes,6,opt,name=profile_surname,json=profileSurname,proto3" json:"profile_surname,omitempty"`
	RoleId         int32                  `protobuf:"varint,7,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName       string                 `protobuf:"bytes,8,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	IsMuted        bool                   `protobuf:"varint,9,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	IsTyping       bool                   `protobuf:"varint,10,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomGeneral) Reset() {
	*x = RoomGeneral{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGeneral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGeneral) ProtoMessage() {}

func (x *RoomGeneral) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGeneral.ProtoReflect.Descriptor instead.
func (*RoomGeneral) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *RoomGeneral) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomGeneral) GetRoomTile() string {
	if x != nil {
		return x.RoomTile
	}
	return ""
}

func (x *RoomGeneral) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *RoomGeneral) GetProfileId() int32 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *RoomGeneral) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *RoomGeneral) GetProfileSurname() string {
	if x != nil {
		return x.ProfileSurname
	}
	return ""
}

func (x *RoomGeneral) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoomGeneral) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoomGeneral) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *RoomGeneral) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

type ChatsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int32                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatsListRequest) Reset() {
	*x = ChatsListRequest{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatsListRequest) ProtoMessage() {}

func (x *ChatsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatsListRequest.ProtoReflect.Descriptor instead.
func (*ChatsListRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *ChatsListRequest) GetProfileId() int32 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type Chat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MyProfileId    int32                  `protobuf:"varint,1,opt,name=my_profile_id,json=myProfileId,proto3" json:"my_profile_id,omitempty"`
	User2ProfileId int32                  `protobuf:"varint,2,opt,name=user2_profile_id,json=user2ProfileId,proto3" json:"user2_profile_id,omitempty"`
	LastMessage    string                 `protobuf:"bytes,3,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	IsRead         bool                   `protobuf:"varint,4,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CountNewMsg    int32                  `protobuf:"varint,5,opt,name=count_new_msg,json=countNewMsg,proto3" json:"count_new_msg,omitempty"`
	IsVisible      bool                   `protobuf:"varint,6,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *Chat) GetMyProfileId() int32 {
	if x != nil {
		return x.MyProfileId
	}
	return 0
}

func (x *Chat) GetUser2ProfileId() int32 {
	if x != nil {
		return x.User2ProfileId
	}
	return 0
}

func (x *Chat) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

func (x *Chat) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Chat) GetCountNewMsg() int32 {
	if x != nil {
		return x.CountNewMsg
	}
	return 0
}

func (x *Chat) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

type ChatsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatsListResponse) Reset() {
	*x = ChatsListResponse{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatsListResponse) ProtoMessage() {}

func (x *ChatsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatsListResponse.ProtoReflect.Descriptor instead.
func (*ChatsListResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *ChatsListResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    int32                  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageRequest) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageRequest) GetReceiverId() int32 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User1Id       int32                  `protobuf:"varint,1,opt,name=user1_id,json=user1Id,proto3" json:"user1_id,omitempty"`
	User2Id       int32                  `protobuf:"varint,2,opt,name=user2_id,json=user2Id,proto3" json:"user2_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessageRequest) GetUser1Id() int32 {
	if x != nil {
		return x.User1Id
	}
	return 0
}

func (x *GetMessageRequest) GetUser2Id() int32 {
	if x != nil {
		return x.User2Id
	}
	return 0
}

type GetMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageResponse) Reset() {
	*x = GetMessageResponse{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResponse) ProtoMessage() {}

func (x *GetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResponse.ProtoReflect.Descriptor instead.
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *GetMessageResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId      int32                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    int32                  `protobuf:"varint,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *Message) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetReceiverId() int32 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x05proto\"0\n" +
	"\x0fRoomListRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x05R\tprofileId\"I\n" +
	"\x10RoomListResponse\x125\n" +
	"\froom_general\x18\x01 \x03(\v2\x12.proto.RoomGeneralR\vroomGeneral\"\xb9\x02\n" +
	"\vRoomGeneral\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\x12\x1b\n" +
	"\troom_tile\x18\x02 \x01(\tR\broomTile\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x05R\bclientId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x04 \x01(\x05R\tprofileId\x12!\n" +
	"\fprofile_name\x18\x05 \x01(\tR\vprofileName\x12'\n" +
	"\x0fprofile_surname\x18\x06 \x01(\tR\x0eprofileSurname\x12\x17\n" +
	"\arole_id\x18\a \x01(\x05R\x06roleId\x12\x1b\n" +
	"\trole_name\x18\b \x01(\tR\broleName\x12\x19\n" +
	"\bis_muted\x18\t \x01(\bR\aisMuted\x12\x1b\n" +
	"\tis_typing\x18\n" +
	" \x01(\bR\bisTyping\"1\n" +
	"\x10ChatsListRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x05R\tprofileId\"\xd3\x01\n" +
	"\x04Chat\x12\"\n" +
	"\rmy_profile_id\x18\x01 \x01(\x05R\vmyProfileId\x12(\n" +
	"\x10user2_profile_id\x18\x02 \x01(\x05R\x0euser2ProfileId\x12!\n" +
	"\flast_message\x18\x03 \x01(\tR\vlastMessage\x12\x17\n" +
	"\ais_read\x18\x04 \x01(\bR\x06isRead\x12\"\n" +
	"\rcount_new_msg\x18\x05 \x01(\x05R\vcountNewMsg\x12\x1d\n" +
	"\n" +
	"is_visible\x18\x06 \x01(\bR\tisVisible\"6\n" +
	"\x11ChatsListResponse\x12!\n" +
	"\x05chats\x18\x01 \x03(\v2\v.proto.ChatR\x05chats\"f\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\x05R\n" +
	"receiverId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"/\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x11GetMessageRequest\x12\x19\n" +
	"\buser1_id\x18\x01 \x01(\x05R\auser1Id\x12\x19\n" +
	"\buser2_id\x18\x02 \x01(\x05R\auser2Id\"@\n" +
	"\x12GetMessageResponse\x12*\n" +
	"\bmessages\x18\x01 \x03(\v2\x0e.proto.MessageR\bmessages\"\x89\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x05R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\x05R\n" +
	"receiverId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp2\x96\x02\n" +
	"\x0eMessageService\x12;\n" +
	"\bRoomList\x12\x16.proto.RoomListRequest\x1a\x17.proto.RoomListResponse\x12>\n" +
	"\tChatsList\x12\x17.proto.ChatsListRequest\x1a\x18.proto.ChatsListResponse\x12D\n" +
	"\vSendMessage\x12\x19.proto.SendMessageRequest\x1a\x1a.proto.SendMessageResponse\x12A\n" +
	"\n" +
	"GetMessage\x12\x18.proto.GetMessageRequest\x1a\x19.proto.GetMessageResponseB,Z*github.com/almat-kst10/message_micro/protob\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_message_proto_goTypes = []any{
	(*RoomListRequest)(nil),     // 0: proto.RoomListRequest
	(*RoomListResponse)(nil),    // 1: proto.RoomListResponse
	(*RoomGeneral)(nil),         // 2: proto.RoomGeneral
	(*ChatsListRequest)(nil),    // 3: proto.ChatsListRequest
	(*Chat)(nil),                // 4: proto.Chat
	(*ChatsListResponse)(nil),   // 5: proto.ChatsListResponse
	(*SendMessageRequest)(nil),  // 6: proto.SendMessageRequest
	(*SendMessageResponse)(nil), // 7: proto.SendMessageResponse
	(*GetMessageRequest)(nil),   // 8: proto.GetMessageRequest
	(*GetMessageResponse)(nil),  // 9: proto.GetMessageResponse
	(*Message)(nil),             // 10: proto.Message
}
var file_message_proto_depIdxs = []int32{
	2,  // 0: proto.RoomListResponse.room_general:type_name -> proto.RoomGeneral
	4,  // 1: proto.ChatsListResponse.chats:type_name -> proto.Chat
	10, // 2: proto.GetMessageResponse.messages:type_name -> proto.Message
	0,  // 3: proto.MessageService.RoomList:input_type -> proto.RoomListRequest
	3,  // 4: proto.MessageService.ChatsList:input_type -> proto.ChatsListRequest
	6,  // 5: proto.MessageService.SendMessage:input_type -> proto.SendMessageRequest
	8,  // 6: proto.MessageService.GetMessage:input_type -> proto.GetMessageRequest
	1,  // 7: proto.MessageService.RoomList:output_type -> proto.RoomListResponse
	5,  // 8: proto.MessageService.ChatsList:output_type -> proto.ChatsListResponse
	7,  // 9: proto.MessageService.SendMessage:output_type -> proto.SendMessageResponse
	9,  // 10: proto.MessageService.GetMessage:output_type -> proto.GetMessageResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
