// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int32                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListRequest) Reset() {
	*x = RoomListRequest{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListRequest) ProtoMessage() {}

func (x *RoomListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListRequest.ProtoReflect.Descriptor instead.
func (*RoomListRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *RoomListRequest) GetProfileId() int32 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type RoomListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomGeneral   []*RoomGeneral         `protobuf:"bytes,1,rep,name=room_general,json=roomGeneral,proto3" json:"room_general,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListResponse) Reset() {
	*x = RoomListResponse{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListResponse) ProtoMessage() {}

func (x *RoomListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListResponse.ProtoReflect.Descriptor instead.
func (*RoomListResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *RoomListResponse) GetRoomGeneral() []*RoomGeneral {
	if x != nil {
		return x.RoomGeneral
	}
	return nil
}

type RoomGeneral struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomTile      string                 `protobuf:"bytes,2,opt,name=room_tile,json=roomTile,proto3" json:"room_tile,omitempty"`
	ClientId      int32                  `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ProfileId     int32                  `protobuf:"varint,4,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	RoleId        int32                  `protobuf:"varint,7,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,8,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	IsMuted       bool                   `protobuf:"varint,9,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	IsTyping      bool                   `protobuf:"varint,10,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGeneral) Reset() {
	*x = RoomGeneral{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGeneral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGeneral) ProtoMessage() {}

func (x *RoomGeneral) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGeneral.ProtoReflect.Descriptor instead.
func (*RoomGeneral) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *RoomGeneral) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomGeneral) GetRoomTile() string {
	if x != nil {
		return x.RoomTile
	}
	return ""
}

func (x *RoomGeneral) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *RoomGeneral) GetProfileId() int32 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *RoomGeneral) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoomGeneral) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoomGeneral) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *RoomGeneral) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

type RoomCreatePersonRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FirstProfileId  int32                  `protobuf:"varint,1,opt,name=first_profile_id,json=firstProfileId,proto3" json:"first_profile_id,omitempty"`
	SecondProfileId int32                  `protobuf:"varint,2,opt,name=second_profile_id,json=secondProfileId,proto3" json:"second_profile_id,omitempty"`
	RoomTitle       string                 `protobuf:"bytes,3,opt,name=room_title,json=roomTitle,proto3" json:"room_title,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomCreatePersonRequest) Reset() {
	*x = RoomCreatePersonRequest{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreatePersonRequest) ProtoMessage() {}

func (x *RoomCreatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreatePersonRequest.ProtoReflect.Descriptor instead.
func (*RoomCreatePersonRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *RoomCreatePersonRequest) GetFirstProfileId() int32 {
	if x != nil {
		return x.FirstProfileId
	}
	return 0
}

func (x *RoomCreatePersonRequest) GetSecondProfileId() int32 {
	if x != nil {
		return x.SecondProfileId
	}
	return 0
}

func (x *RoomCreatePersonRequest) GetRoomTitle() string {
	if x != nil {
		return x.RoomTitle
	}
	return ""
}

type RoomCreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int32                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	RoomTitle     string                 `protobuf:"bytes,2,opt,name=room_title,json=roomTitle,proto3" json:"room_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreateGroupRequest) Reset() {
	*x = RoomCreateGroupRequest{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateGroupRequest) ProtoMessage() {}

func (x *RoomCreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateGroupRequest.ProtoReflect.Descriptor instead.
func (*RoomCreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *RoomCreateGroupRequest) GetProfileId() int32 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *RoomCreateGroupRequest) GetRoomTitle() string {
	if x != nil {
		return x.RoomTitle
	}
	return ""
}

type RoomCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreateResponse) Reset() {
	*x = RoomCreateResponse{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateResponse) ProtoMessage() {}

func (x *RoomCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateResponse.ProtoReflect.Descriptor instead.
func (*RoomCreateResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *RoomCreateResponse) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type RoomDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomDeleteRequest) Reset() {
	*x = RoomDeleteRequest{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDeleteRequest) ProtoMessage() {}

func (x *RoomDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDeleteRequest.ProtoReflect.Descriptor instead.
func (*RoomDeleteRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *RoomDeleteRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type RoomDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomDeleteResponse) Reset() {
	*x = RoomDeleteResponse{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDeleteResponse) ProtoMessage() {}

func (x *RoomDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDeleteResponse.ProtoReflect.Descriptor instead.
func (*RoomDeleteResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *RoomDeleteResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ListMessageByRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ProfileId     int32                  `protobuf:"varint,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageByRoomRequest) Reset() {
	*x = ListMessageByRoomRequest{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageByRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageByRoomRequest) ProtoMessage() {}

func (x *ListMessageByRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageByRoomRequest.ProtoReflect.Descriptor instead.
func (*ListMessageByRoomRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *ListMessageByRoomRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ListMessageByRoomRequest) GetProfileId() int32 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type GetListMessageByRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []*Message             `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListMessageByRoomResponse) Reset() {
	*x = GetListMessageByRoomResponse{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListMessageByRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListMessageByRoomResponse) ProtoMessage() {}

func (x *GetListMessageByRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListMessageByRoomResponse.ProtoReflect.Descriptor instead.
func (*GetListMessageByRoomResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *GetListMessageByRoomResponse) GetMessage() []*Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        int32                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ProfileId     int32                  `protobuf:"varint,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *Message) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Message) GetProfileId() int32 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *Message) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ProfileId     int32                  `protobuf:"varint,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMessageRequest) Reset() {
	*x = SetMessageRequest{}
	mi := &file_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMessageRequest) ProtoMessage() {}

func (x *SetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMessageRequest.ProtoReflect.Descriptor instead.
func (*SetMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{11}
}

func (x *SetMessageRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SetMessageRequest) GetProfileId() int32 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *SetMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SetMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMessageResponse) Reset() {
	*x = SetMessageResponse{}
	mi := &file_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMessageResponse) ProtoMessage() {}

func (x *SetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMessageResponse.ProtoReflect.Descriptor instead.
func (*SetMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{12}
}

func (x *SetMessageResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type SetMessageAiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ProfileId     int32                  `protobuf:"varint,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMessageAiRequest) Reset() {
	*x = SetMessageAiRequest{}
	mi := &file_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMessageAiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMessageAiRequest) ProtoMessage() {}

func (x *SetMessageAiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMessageAiRequest.ProtoReflect.Descriptor instead.
func (*SetMessageAiRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{13}
}

func (x *SetMessageAiRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SetMessageAiRequest) GetProfileId() int32 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *SetMessageAiRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SetMessageAiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMessageAiResponse) Reset() {
	*x = SetMessageAiResponse{}
	mi := &file_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMessageAiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMessageAiResponse) ProtoMessage() {}

func (x *SetMessageAiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMessageAiResponse.ProtoReflect.Descriptor instead.
func (*SetMessageAiResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{14}
}

func (x *SetMessageAiResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GetMessageAiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ProfileId     int32                  `protobuf:"varint,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageAiRequest) Reset() {
	*x = GetMessageAiRequest{}
	mi := &file_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageAiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageAiRequest) ProtoMessage() {}

func (x *GetMessageAiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageAiRequest.ProtoReflect.Descriptor instead.
func (*GetMessageAiRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{15}
}

func (x *GetMessageAiRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GetMessageAiRequest) GetProfileId() int32 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type GetMessageAiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []*MessageAi           `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageAiResponse) Reset() {
	*x = GetMessageAiResponse{}
	mi := &file_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageAiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageAiResponse) ProtoMessage() {}

func (x *GetMessageAiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageAiResponse.ProtoReflect.Descriptor instead.
func (*GetMessageAiResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{16}
}

func (x *GetMessageAiResponse) GetMessage() []*MessageAi {
	if x != nil {
		return x.Message
	}
	return nil
}

type MessageAi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        int32                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAi) Reset() {
	*x = MessageAi{}
	mi := &file_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAi) ProtoMessage() {}

func (x *MessageAi) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAi.ProtoReflect.Descriptor instead.
func (*MessageAi) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{17}
}

func (x *MessageAi) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageAi) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MessageAi) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageAi) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x05proto\"0\n" +
	"\x0fRoomListRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x05R\tprofileId\"I\n" +
	"\x10RoomListResponse\x125\n" +
	"\froom_general\x18\x01 \x03(\v2\x12.proto.RoomGeneralR\vroomGeneral\"\xed\x01\n" +
	"\vRoomGeneral\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\x12\x1b\n" +
	"\troom_tile\x18\x02 \x01(\tR\broomTile\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x05R\bclientId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x04 \x01(\x05R\tprofileId\x12\x17\n" +
	"\arole_id\x18\a \x01(\x05R\x06roleId\x12\x1b\n" +
	"\trole_name\x18\b \x01(\tR\broleName\x12\x19\n" +
	"\bis_muted\x18\t \x01(\bR\aisMuted\x12\x1b\n" +
	"\tis_typing\x18\n" +
	" \x01(\bR\bisTyping\"\x8e\x01\n" +
	"\x17RoomCreatePersonRequest\x12(\n" +
	"\x10first_profile_id\x18\x01 \x01(\x05R\x0efirstProfileId\x12*\n" +
	"\x11second_profile_id\x18\x02 \x01(\x05R\x0fsecondProfileId\x12\x1d\n" +
	"\n" +
	"room_title\x18\x03 \x01(\tR\troomTitle\"V\n" +
	"\x16RoomCreateGroupRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x05R\tprofileId\x12\x1d\n" +
	"\n" +
	"room_title\x18\x02 \x01(\tR\troomTitle\",\n" +
	"\x12RoomCreateResponse\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x05R\x06roomId\",\n" +
	"\x11RoomDeleteRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\",\n" +
	"\x12RoomDeleteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"R\n" +
	"\x18ListMessageByRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\x05R\tprofileId\"H\n" +
	"\x1cGetListMessageByRoomResponse\x12(\n" +
	"\amessage\x18\x01 \x03(\v2\x0e.proto.MessageR\amessage\"\xa1\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x05R\x06roomId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\x05R\tprofileId\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"_\n" +
	"\x11SetMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\x05R\tprofileId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\",\n" +
	"\x12SetMessageResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"a\n" +
	"\x13SetMessageAiRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\x05R\tprofileId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\".\n" +
	"\x14SetMessageAiResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"M\n" +
	"\x13GetMessageAiRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\x05R\tprofileId\"B\n" +
	"\x14GetMessageAiResponse\x12*\n" +
	"\amessage\x18\x01 \x03(\v2\x10.proto.MessageAiR\amessage\"g\n" +
	"\tMessageAi\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x05R\x06roomId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt2\xdc\x04\n" +
	"\x0eMessageService\x12;\n" +
	"\bRoomList\x12\x16.proto.RoomListRequest\x1a\x17.proto.RoomListResponse\x12M\n" +
	"\x10RoomCreatePerson\x12\x1e.proto.RoomCreatePersonRequest\x1a\x19.proto.RoomCreateResponse\x12K\n" +
	"\x0fRoomCreateGroup\x12\x1d.proto.RoomCreateGroupRequest\x1a\x19.proto.RoomCreateResponse\x12A\n" +
	"\n" +
	"RoomDelete\x12\x18.proto.RoomDeleteRequest\x1a\x19.proto.RoomDeleteResponse\x12Y\n" +
	"\x11ListMessageByRoom\x12\x1f.proto.ListMessageByRoomRequest\x1a#.proto.GetListMessageByRoomResponse\x12A\n" +
	"\n" +
	"SetMessage\x12\x18.proto.SetMessageRequest\x1a\x19.proto.SetMessageResponse\x12G\n" +
	"\fSetMessageAi\x12\x1a.proto.SetMessageAiRequest\x1a\x1b.proto.SetMessageAiResponse\x12G\n" +
	"\fGetMessageAi\x12\x1a.proto.GetMessageAiRequest\x1a\x1b.proto.GetMessageAiResponseB,Z*github.com/almat-kst10/message_micro/protob\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_message_proto_goTypes = []any{
	(*RoomListRequest)(nil),              // 0: proto.RoomListRequest
	(*RoomListResponse)(nil),             // 1: proto.RoomListResponse
	(*RoomGeneral)(nil),                  // 2: proto.RoomGeneral
	(*RoomCreatePersonRequest)(nil),      // 3: proto.RoomCreatePersonRequest
	(*RoomCreateGroupRequest)(nil),       // 4: proto.RoomCreateGroupRequest
	(*RoomCreateResponse)(nil),           // 5: proto.RoomCreateResponse
	(*RoomDeleteRequest)(nil),            // 6: proto.RoomDeleteRequest
	(*RoomDeleteResponse)(nil),           // 7: proto.RoomDeleteResponse
	(*ListMessageByRoomRequest)(nil),     // 8: proto.ListMessageByRoomRequest
	(*GetListMessageByRoomResponse)(nil), // 9: proto.GetListMessageByRoomResponse
	(*Message)(nil),                      // 10: proto.Message
	(*SetMessageRequest)(nil),            // 11: proto.SetMessageRequest
	(*SetMessageResponse)(nil),           // 12: proto.SetMessageResponse
	(*SetMessageAiRequest)(nil),          // 13: proto.SetMessageAiRequest
	(*SetMessageAiResponse)(nil),         // 14: proto.SetMessageAiResponse
	(*GetMessageAiRequest)(nil),          // 15: proto.GetMessageAiRequest
	(*GetMessageAiResponse)(nil),         // 16: proto.GetMessageAiResponse
	(*MessageAi)(nil),                    // 17: proto.MessageAi
}
var file_message_proto_depIdxs = []int32{
	2,  // 0: proto.RoomListResponse.room_general:type_name -> proto.RoomGeneral
	10, // 1: proto.GetListMessageByRoomResponse.message:type_name -> proto.Message
	17, // 2: proto.GetMessageAiResponse.message:type_name -> proto.MessageAi
	0,  // 3: proto.MessageService.RoomList:input_type -> proto.RoomListRequest
	3,  // 4: proto.MessageService.RoomCreatePerson:input_type -> proto.RoomCreatePersonRequest
	4,  // 5: proto.MessageService.RoomCreateGroup:input_type -> proto.RoomCreateGroupRequest
	6,  // 6: proto.MessageService.RoomDelete:input_type -> proto.RoomDeleteRequest
	8,  // 7: proto.MessageService.ListMessageByRoom:input_type -> proto.ListMessageByRoomRequest
	11, // 8: proto.MessageService.SetMessage:input_type -> proto.SetMessageRequest
	13, // 9: proto.MessageService.SetMessageAi:input_type -> proto.SetMessageAiRequest
	15, // 10: proto.MessageService.GetMessageAi:input_type -> proto.GetMessageAiRequest
	1,  // 11: proto.MessageService.RoomList:output_type -> proto.RoomListResponse
	5,  // 12: proto.MessageService.RoomCreatePerson:output_type -> proto.RoomCreateResponse
	5,  // 13: proto.MessageService.RoomCreateGroup:output_type -> proto.RoomCreateResponse
	7,  // 14: proto.MessageService.RoomDelete:output_type -> proto.RoomDeleteResponse
	9,  // 15: proto.MessageService.ListMessageByRoom:output_type -> proto.GetListMessageByRoomResponse
	12, // 16: proto.MessageService.SetMessage:output_type -> proto.SetMessageResponse
	14, // 17: proto.MessageService.SetMessageAi:output_type -> proto.SetMessageAiResponse
	16, // 18: proto.MessageService.GetMessageAi:output_type -> proto.GetMessageAiResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
